### ISSUE TITLE
The build on MPLAB X IDE does not start

### ISSUE THREAD

**Issue by lexis-megavolt** [fabio-d/xc16plusplus#3]
I have a problem.
In the project I use PIC24, I have a lot of source codes written in C++. I know that XC16 does not support cpp, but I found your revision.
I did everything according to the instructions, the create_xc16plusplus_symlinks.cmd script worked without errors. But the problem is that when I add a file with the cpp extension to the MPLAB X IDE project (5.45 windows) then clicking on the BUILD button does not lead to anything. It's like I'm not pressing the button.
If you remove the file with the extension. cpp, then the build is started and everything is compiled .
I think the problem is in the settings of the MPLAB X IDE for XC16.
Because in another project on XC32 everything works.
I ask for your help.
Thank you in advance.

**Comment by fabio-d** [comment]
Hi! Unfortunately the MPLAB X IDE does not work with C++ out of the box, because it assumes that XC16 can only compile C code.

However, you can import XC16++'s example project as a **User Makefile Project** and workaround the issue. These are the steps that I tested (on MPLAB X v5.30):

- Open MPLAB X and click on *File → New Project*, then select **User Makefile Project**.
![img01](https://user-images.githubusercontent.com/5803506/127398260-f69bba25-0b8c-4623-a1cb-89583b11663e.png)

 - In the next screen, select **dsPIC33FJ128MC804**. Please select this even if you are targeting a different microcontroller, in order to test that at least the example project builds. You will be able to change it later.
![img02](https://user-images.githubusercontent.com/5803506/127398308-b19d1525-06ef-4e20-95ff-accc2151b26f.png)

 - In the next screen, select your programmer.
![img03](https://user-images.githubusercontent.com/5803506/127398334-54f30185-be35-4e50-a0bd-3113d0e957a8.png)

 - In the next screen, type **example-project** as the *Project Name*, browse to the proper *Project Location* and check the *Use project location as the project folder* flag.
![img04](https://user-images.githubusercontent.com/5803506/127398400-21ec5865-292b-48fa-bc2a-8cce9f3fc041.png)

 - And now the last wizard screen, which is the most critical one: type **.** (a single dot) as *Working Directory*, **make all** as *Build command* (and also as *Debug build command*), **make clean** as *Clean command*, **result.elf** as *Image name* (and also as *Debug image name*), then click *Finish*.
![img05](https://user-images.githubusercontent.com/5803506/127398430-736778d4-4bb2-4269-82b2-629a1f91a86e.png)

 - Now navigate to the project folder, **delete the Makefile created by MPLAB X** and extract XC16++'s example project files (you can find them in the XC16++ ZIP file you already downloaded).
![img06](https://user-images.githubusercontent.com/5803506/127398484-2ad5a542-85fc-4d0f-bc21-c69462000ec8.png)

 - Go back to MPLAB X and build the project (*Production → Build Main Project*), it will build successfully! Optionally, you can manually add source files to the project so that they show up in the IDE (right-click on a folder in the *Project* tab, then select *Add Existing Item* and choose the relevant file/files).
![img07](https://user-images.githubusercontent.com/5803506/127398504-9a814895-0143-41b4-bf30-017f2130386c.png)
 
 - Lastly, edit the first lines in the Makefile to select the microcontroller you are actually targeting. Select the target microcontroller in the *File → Project Properties* dialog too, and run *Production → Clean and Build Main Project*.
![img08](https://user-images.githubusercontent.com/5803506/127398525-05f802b2-d6a5-436d-ac20-fac51f32d8a1.png)

You are now ready to customize the example project to you needs! Keep in mind that, if you add or remove source files, you will have to edit the ``OBJS`` variable in the Makefile accordingly (it must be a list of all the source files, with .o extension instead of .c/.cpp).

**Comment by lexis-megavolt** [comment]
Thank you very much for deciding to help me.
I did everything according to your instructions.
But I have a compilation error:
[image: image.png]
[image: image.png]

I apologize again. But I do not know what to do next.



чт, 29 июл. 2021 г. в 00:33, fabio-d ***@***.***>:

**Comment by lexis-megavolt** [comment]
I'm sorry.
I figured out the problem. I had the path to the compiler specified
incorrectly.
Thank you for participating.

чт, 29 июл. 2021 г. в 14:24, Алексей Тарасенко ***@***.***>:
